import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { PortfolioCoverImage } from '@/components/portfolio-cover-image'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight, ExternalLink } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { CtaBand } from '@/components/cta-band'
import { categoryLabel, designationLabel, getPublishedProject, getPublishedProjects, projectImage } from '@/lib/portfolio'
import { siteConfig, siteUrl } from '@/lib/site-config'

type Props = { params: Promise<{ slug: string }> }
export const dynamic = 'force-dynamic'

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params; const project = await getPublishedProject(slug)
  if (!project) return { title: 'Project not found', robots: { index: false, follow: false } }
  const title = project.seo_title || `${project.title} — ${siteConfig.name}`; const description = project.meta_description || project.short_summary
  return { title, description, robots: project.indexing === 'noindex' ? { index: false, follow: true } : undefined, alternates: { canonical: project.canonical_url || `${siteUrl}/work/${project.slug}` }, openGraph: { title: project.social_sharing_title || title, description: project.social_sharing_description || description, url: `${siteUrl}/work/${project.slug}`, type: 'article', images: [{ url: project.social_sharing_image || projectImage(project), alt: project.cover_image_alt || project.title }] }, twitter: { card: 'summary_large_image', title: project.social_sharing_title || title, description: project.social_sharing_description || description, images: [project.social_sharing_image || projectImage(project)] } }
}

function Narrative({ title, value, visible = true }: { title: string; value: string | null; visible?: boolean }) { return visible && value ? <section className="flex flex-col gap-3"><h2 className="text-xl font-semibold">{title}</h2><p className="leading-relaxed text-muted-foreground">{value}</p></section> : null }
function ChipList({ title, values, visible = true }: { title: string; values: string[]; visible?: boolean }) { return visible && values.length > 0 ? <section className="flex flex-col gap-4"><h2 className="text-xl font-semibold">{title}</h2><div className="flex flex-wrap gap-2">{values.map((value) => <Badge key={value} variant="secondary">{categoryLabel(value)}</Badge>)}</div></section> : null }

export default async function ProjectPage({ params }: Props) {
  const { slug } = await params; const [project, all] = await Promise.all([getPublishedProject(slug), getPublishedProjects('work')])
  if (!project) notFound()
  const index = all.findIndex((item) => item.slug === project.slug); const previous = index > 0 ? all[index - 1] : null; const next = index >= 0 && index < all.length - 1 ? all[index + 1] : null
  const jsonLd = { '@context': 'https://schema.org', '@type': 'CreativeWork', name: project.title, description: project.short_summary, url: `${siteUrl}/work/${project.slug}`, image: projectImage(project), dateCreated: project.project_date || undefined, genre: categoryLabel(project.primary_category), creator: { '@id': `${siteUrl}/#organization` } }
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <article>
      <header className="border-b border-border bg-card/40"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-4 py-14 sm:px-6 lg:py-20"><Link href="/work" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft data-icon="inline-start" />Back to Work</Link><div className="flex flex-wrap gap-2"><Badge variant="outline">{designationLabel(project.designation)}</Badge><Badge variant="secondary">{categoryLabel(project.primary_category)}</Badge>{project.primary_market && <Badge variant="secondary">{project.primary_market}</Badge>}</div><h1 className="max-w-4xl text-4xl font-semibold tracking-tight sm:text-5xl">{project.title}</h1><p className="max-w-3xl text-lg leading-relaxed text-muted-foreground">{project.short_summary}</p>{project.designation === 'internal' && <p className="max-w-2xl text-sm font-medium leading-relaxed text-primary">Built on Our Own System — an internal RRD project demonstrating the systems we use ourselves.</p>}</div></header>
      <div className="mx-auto grid max-w-6xl gap-12 px-4 py-12 sm:px-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(16rem,0.7fr)] lg:py-16"><div className="flex flex-col gap-12"><PortfolioCoverImage src={projectImage(project)} alt={project.cover_image_alt || project.title} priority sizes="(min-width: 1024px) 66vw, 100vw" className="border border-border bg-card" /><Narrative title="Project overview" value={project.project_overview} /><div className="grid gap-10 md:grid-cols-2"><Narrative title="Challenge" value={project.challenge} visible={project.show_challenge} /><Narrative title="Strategy & approach" value={project.creative_approach} visible={project.show_strategy} /><Narrative title="Intended purpose" value={project.intended_purpose} visible={project.show_purpose} /><Narrative title="Verified outcome" value={project.verified_outcome} visible={project.show_outcome} /></div><ChipList title="Core capabilities demonstrated" values={project.core_capabilities} visible={project.show_capabilities} />{project.show_deliverables && project.deliverables.length > 0 && <section className="flex flex-col gap-4"><h2 className="text-xl font-semibold">Deliverables</h2><ul className="grid gap-3 text-muted-foreground sm:grid-cols-2">{project.deliverables.map((item) => <li key={item} className="border-l-2 border-primary pl-3">{item}</li>)}</ul></section>}<Narrative title="How This Translates to Other Markets" value={project.market_translation} visible={project.show_market_translation} /><ChipList title="Applicable industries" values={project.applicable_industries} visible={project.show_applicable_industries} />{project.gallery.length > 0 && <section className="flex flex-col gap-5"><h2 className="text-xl font-semibold">Project gallery</h2><div className="grid gap-5 sm:grid-cols-2">{project.gallery.map((image, imageIndex) => <figure key={`${image.url}-${imageIndex}`} className="flex flex-col gap-2"><div className="relative aspect-square overflow-hidden border border-border"><Image src={image.url} alt={image.alt || `${project.title} gallery image ${imageIndex + 1}`} fill sizes="(min-width: 640px) 50vw, 100vw" className="object-cover" /></div>{image.caption && <figcaption className="text-sm text-muted-foreground">{image.caption}</figcaption>}</figure>)}</div></section>}</div>
        <aside className="flex h-fit flex-col gap-8 border-l border-border pl-6"><div className="flex flex-col gap-3"><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Project details</h2>{project.primary_market && <p className="text-sm"><span className="text-muted-foreground">Market: </span>{project.primary_market}</p>}{project.client_type && <p className="text-sm"><span className="text-muted-foreground">Client type: </span>{project.client_type}</p>}{project.show_client_name && project.client_name && <p className="text-sm"><span className="text-muted-foreground">Client: </span>{project.client_name}</p>}</div>{project.show_live_project_link && project.live_project_url && <Button render={<a href={project.live_project_url} target="_blank" rel="noreferrer" />} className="w-full">{project.cta_label || 'Visit Project'}<ExternalLink data-icon="inline-end" /></Button>}{project.demo_url && <Link href={project.demo_url} target="_blank" className="text-sm text-primary hover:underline">View demo</Link>}{project.repository_url && <Link href={project.repository_url} target="_blank" className="text-sm text-primary hover:underline">View repository</Link>}</aside></div>
    </article>
    {(previous || next) && <nav className="border-t border-border" aria-label="Project navigation"><div className="mx-auto flex max-w-6xl justify-between gap-6 px-4 py-8 sm:px-6">{previous ? <Link href={`/work/${previous.slug}`} className="flex max-w-[45%] flex-col gap-1 text-sm hover:text-primary"><span className="text-muted-foreground">Previous</span><span className="font-semibold">{previous.title}</span></Link> : <span />}{next && <Link href={`/work/${next.slug}`} className="flex max-w-[45%] flex-col items-end gap-1 text-right text-sm hover:text-primary"><span className="text-muted-foreground">Next</span><span className="font-semibold">{next.title}</span></Link>}</div></nav>}
    <CtaBand title="Have a project in mind?" primaryLabel={siteConfig.cta.start} />
  </>
}
