'use client'

import Link from 'next/link'
import { useState } from 'react'
import { updatePricingCapability } from '@/app/actions/pricing-admin'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import type { PricingCapability } from '@/lib/pricing-shared'

function Field({ label, name, value, type = 'text' }: { label: string; name: string; value: string | number; type?: string }) { return <label className="flex flex-col gap-2 text-sm"><span className="font-medium">{label}</span><Input name={name} type={type} defaultValue={value} /></label> }

export function CapabilityEditor({ capability }: { capability: PricingCapability }) {
  const [status, setStatus] = useState('')
  async function submit(formData: FormData) { setStatus('Saving…'); try { await updatePricingCapability(formData); setStatus('Saved.') } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save.') } }
  return <main className="min-h-dvh bg-muted/20 px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto max-w-4xl"><header className="flex flex-col gap-4 border-b border-border pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Capability settings</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{capability.name}</h1><p className="mt-2 text-sm text-muted-foreground">Edit the internal assumptions used by the estimator. These values never enter public client payloads.</p></div><Button variant="outline" render={<Link href="/admin/pricing" />}>Back to pricing</Button></header><form action={submit} className="mt-8 flex flex-col gap-6 rounded-lg border border-border bg-card p-5 sm:p-8"><input type="hidden" name="id" value={capability.id} /><div className="grid gap-5 md:grid-cols-2"><Field label="Name" name="name" value={capability.name} /><Field label="Description" name="description" value={capability.description} /></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Internal base" name="internalBasePrice" type="number" value={capability.internalBasePrice} /><Field label="Minimum price" name="minimumPrice" type="number" value={capability.minimumPrice} /><Field label="Suggested low" name="suggestedLowPrice" type="number" value={capability.suggestedLowPrice} /><Field label="Suggested high" name="suggestedHighPrice" type="number" value={capability.suggestedHighPrice} /></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><label className="flex flex-col gap-2 text-sm"><span className="font-medium">Complexity</span><select name="complexity" defaultValue={capability.complexity} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>Low</option><option>Medium</option><option>High</option><option>Custom</option></select></label><Field label="Hours low" name="estimatedHoursLow" type="number" value={capability.estimatedHoursLow} /><Field label="Hours high" name="estimatedHoursHigh" type="number" value={capability.estimatedHoursHigh} /><label className="flex flex-col gap-2 text-sm"><span className="font-medium">Support impact</span><select name="monthlySupportImpact" defaultValue={capability.monthlySupportImpact} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>None</option><option>Low</option><option>Medium</option><option>High</option><option>Variable</option></select></label></div><label className="flex flex-col gap-2 text-sm"><span className="font-medium">Internal notes</span><textarea name="internalNotes" defaultValue={capability.internalNotes} rows={6} className="rounded-md border border-input bg-background px-3 py-2 text-sm" /></label><div className="flex flex-wrap items-center gap-3"><Button type="submit">Save capability</Button>{status && <span className="text-sm text-muted-foreground" role="status">{status}</span>}</div></form></div></main>
}
