'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { Check } from 'lucide-react'
import { createEstimate } from '@/app/actions/pricing'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { complexityMultipliers, formatCurrency, pricingIndustries, suggestedCapabilities, type PricingCapability, type PricingPlatform, type RecurringService } from '@/lib/pricing-shared'

type SelectedItem = { capabilityId: string; quantity: number; override: string; discount: number; internalNote: string; clientNote: string }

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-2 text-sm"><span className="font-medium">{label}</span>{children}</label> }

export function EstimateBuilder({ capabilities, platforms, recurringServices }: { capabilities: PricingCapability[]; platforms: PricingPlatform[]; recurringServices: RecurringService[] }) {
  const [industry, setIndustry] = useState('solar')
  const [projectType, setProjectType] = useState('')
  const [platformId, setPlatformId] = useState(platforms[0]?.id || '')
  const [items, setItems] = useState<SelectedItem[]>([])
  const [recurring, setRecurring] = useState<string[]>([])
  const [clientName, setClientName] = useState('')
  const [company, setCompany] = useState('')
  const [contact, setContact] = useState('')
  const [customLabor, setCustomLabor] = useState(0)
  const [contingency, setContingency] = useState(0)
  const [discount, setDiscount] = useState(0)
  const [tax, setTax] = useState(0)
  const [complexity, setComplexity] = useState<'Low' | 'Medium' | 'High' | 'Custom'>('Medium')
  const [status, setStatus] = useState('')
  const [saving, setSaving] = useState(false)
  const [notes, setNotes] = useState('')
  const selectedCapabilities = items.map((item) => capabilities.find((capability) => capability.id === item.capabilityId)).filter(Boolean) as PricingCapability[]
  const platform = platforms.find((item) => item.id === platformId)
  const recommended = useMemo(() => new Set(suggestedCapabilities(capabilities, industry)), [capabilities, industry])
  const grouped = useMemo(() => capabilities.reduce<Record<string, PricingCapability[]>>((groups, item) => { (groups[item.category] ||= []).push(item); return groups }, {}), [capabilities])
  const basePrice = platform?.suggestedLowPrice || 0
  const capabilitySubtotal = items.reduce((sum, item) => { const capability = capabilities.find((entry) => entry.id === item.capabilityId); if (!capability) return sum; return sum + (Number(item.override) || capability.internalBasePrice) * item.quantity - item.discount }, 0)
  const beforeAdjustment = basePrice + capabilitySubtotal + customLabor
  const multiplier = complexity === 'Custom' ? 1 : complexityMultipliers[complexity]
  const complexityAdjustment = beforeAdjustment * (multiplier - 1)
  const subtotal = beforeAdjustment + complexityAdjustment
  const contingencyAmount = subtotal * (contingency / 100)
  const total = Math.max(0, subtotal + contingencyAmount - discount + tax)
  const recurringTotal = recurring.reduce((sum, id) => sum + (recurringServices.find((item) => item.id === id)?.monthlyClientPrice || 0), 0)
  const hours = selectedCapabilities.reduce((range, item) => ({ low: range.low + item.estimatedHoursLow, high: range.high + item.estimatedHoursHigh }), { low: 0, high: 0 })

  function toggleCapability(capability: PricingCapability) { setItems((current) => current.some((item) => item.capabilityId === capability.id) ? current.filter((item) => item.capabilityId !== capability.id) : [...current, { capabilityId: capability.id, quantity: 1, override: '', discount: 0, internalNote: '', clientNote: '' }]) }
  async function save() {
    setSaving(true); setStatus('Saving estimate…')
    try {
      const result = await createEstimate({ estimateNumber: `RRD-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`, clientName, company, contact, industrySlug: industry, projectType, platformId, status: 'Draft', expirationDate: '', basePrice, capabilitySubtotal, thirdPartySetupCost: 0, customLabor, complexityAdjustment, contingency: contingencyAmount, discount, tax, totalPrice: total, recurringTotal, estimatedHoursLow: hours.low, estimatedHoursHigh: hours.high, internalCost: Math.round(hours.high * 85), notes, items: items.map((item) => { const capability = capabilities.find((entry) => entry.id === item.capabilityId)!; return { capabilityId: capability.id, label: capability.name, quantity: item.quantity, unitPrice: capability.internalBasePrice, manualPriceOverride: item.override ? Number(item.override) : undefined, discount: item.discount, estimatedHoursLow: capability.estimatedHoursLow, estimatedHoursHigh: capability.estimatedHoursHigh, internalNote: item.internalNote, clientNote: item.clientNote } }) })
      setStatus(`Saved ${result.estimateNumber}.`)
    } catch (error) { setStatus(error instanceof Error ? error.message : 'Estimate could not be saved.') } finally { setSaving(false) }
  }
  return <main className="min-h-dvh bg-muted/20 px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-4 border-b border-border pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Private quote builder</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">New estimate</h1><p className="mt-2 text-sm text-muted-foreground">Choose an industry, let the system suggest scope, then adjust the quote with transparent inputs.</p></div><nav className="flex gap-2"><Button variant="outline" render={<Link href="/admin/pricing" />}>Pricing matrix</Button><Button variant="ghost" render={<Link href="/admin/leads" />}>Leads</Button></nav></header>
    <div className="mt-8 grid items-start gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]">
      <div className="flex flex-col gap-6"><section className="rounded-lg border border-border bg-card p-5"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Field label="Industry"><select value={industry} onChange={(event) => setIndustry(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{pricingIndustries.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select></Field><Field label="Project type"><Input value={projectType} onChange={(event) => setProjectType(event.target.value)} placeholder="Lead generation system" /></Field><Field label="Client / contact"><Input value={clientName} onChange={(event) => setClientName(event.target.value)} placeholder="Client name" /></Field><Field label="Company"><Input value={company} onChange={(event) => setCompany(event.target.value)} placeholder="Company name" /></Field></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Contact details"><Input value={contact} onChange={(event) => setContact(event.target.value)} placeholder="Email or phone" /></Field><Field label="Base platform"><select value={platformId} onChange={(event) => setPlatformId(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{platforms.map((item) => <option key={item.id} value={item.id}>{item.name} · {formatCurrency(item.suggestedLowPrice)}–{formatCurrency(item.suggestedHighPrice)}</option>)}</select></Field></div></section>
        <section className="rounded-lg border border-border bg-card p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Scope library</p><h2 className="mt-1 text-xl font-semibold">Capabilities</h2></div><p className="text-sm text-muted-foreground">{items.length} selected · recommended items are marked</p></div><div className="mt-5 flex flex-col gap-6">{Object.entries(grouped).map(([category, entries]) => <div key={category}><h3 className="text-sm font-semibold">{category}</h3><div className="mt-2 grid gap-2 md:grid-cols-2">{entries.map((capability) => { const selected = items.find((item) => item.capabilityId === capability.id); return <button type="button" key={capability.id} onClick={() => toggleCapability(capability)} className={`flex items-start gap-3 rounded-md border p-3 text-left transition-colors ${selected ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/50'}`}><span className={`mt-0.5 flex size-5 shrink-0 items-center justify-center rounded border ${selected ? 'border-primary bg-primary text-primary-foreground' : 'border-input'}`}>{selected && <Check className="size-3" />}</span><span className="min-w-0"><span className="flex flex-wrap items-center gap-2 font-medium">{capability.name}{recommended.has(capability.slug) && <Badge variant="secondary">Suggested</Badge>}</span><span className="mt-1 block text-xs leading-relaxed text-muted-foreground">{capability.description}</span></span></button> })}</div></div>)}</div></section>
        <section className="rounded-lg border border-border bg-card p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Adjustments</p><h2 className="mt-1 text-xl font-semibold">Make the estimate honest</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Complexity"><select value={complexity} onChange={(event) => setComplexity(event.target.value as typeof complexity)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>Low</option><option>Medium</option><option>High</option><option>Custom</option></select></Field><Field label="Custom labor"><Input type="number" min="0" value={customLabor || ''} onChange={(event) => setCustomLabor(Number(event.target.value) || 0)} placeholder="$0" /></Field><Field label="Contingency %"><Input type="number" min="0" max="100" value={contingency || ''} onChange={(event) => setContingency(Number(event.target.value) || 0)} placeholder="0" /></Field><Field label="Discount"><Input type="number" min="0" value={discount || ''} onChange={(event) => setDiscount(Number(event.target.value) || 0)} placeholder="$0" /></Field></div><div className="mt-5"><Field label="Internal notes"><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={4} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Scope assumptions, risks, and follow-up questions" /></Field></div></section>
        <section className="rounded-lg border border-border bg-card p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Recurring support</p><h2 className="mt-1 text-xl font-semibold">Optional monthly services</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{recurringServices.map((service) => <label key={service.id} className="flex cursor-pointer items-center justify-between gap-3 rounded-md border border-border p-3 text-sm"><span><input type="checkbox" checked={recurring.includes(service.id)} onChange={() => setRecurring((current) => current.includes(service.id) ? current.filter((id) => id !== service.id) : [...current, service.id])} className="mr-2" />{service.name}</span><span className="text-muted-foreground">{formatCurrency(service.monthlyClientPrice)}/mo</span></label>)}</div></section></div>
      <aside className="xl:sticky xl:top-6"><section className="rounded-lg border border-border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Estimate summary</p><h2 className="mt-2 text-2xl font-semibold">{formatCurrency(total)}</h2><p className="mt-1 text-sm text-muted-foreground">{formatCurrency(recurringTotal)} / month optional support</p><div className="mt-6 flex flex-col gap-3 border-t border-border pt-4 text-sm"><div className="flex justify-between gap-4"><span className="text-muted-foreground">Base platform</span><span>{formatCurrency(basePrice)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Capabilities</span><span>{formatCurrency(capabilitySubtotal)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Custom labor</span><span>{formatCurrency(customLabor)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Complexity adjustment</span><span>{formatCurrency(complexityAdjustment)}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Contingency</span><span>{formatCurrency(contingencyAmount)}</span></div>{discount > 0 && <div className="flex justify-between gap-4"><span className="text-muted-foreground">Discount</span><span>−{formatCurrency(discount)}</span></div>}<div className="flex justify-between gap-4 border-t border-border pt-3 font-semibold"><span>Project total</span><span>{formatCurrency(total)}</span></div></div><div className="mt-5 rounded-md bg-muted/50 p-3 text-sm"><p className="font-medium">Implementation effort</p><p className="mt-1 text-muted-foreground">{hours.low}–{hours.high} estimated hours</p></div><Button className="mt-5 w-full" onClick={save} disabled={saving || !items.length}>{saving ? 'Saving…' : 'Save draft estimate'}</Button>{status && <p className="mt-3 text-center text-sm text-muted-foreground" role="status">{status}</p>}</section></aside>
    </div></div></main>
}
