'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowRight, Search, Plus, Check, X } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { formatCurrency, type PricingCapability, type PricingPlatform, type RecurringService } from '@/lib/pricing-shared'

function moneyRange(low: number, high: number) { return `${formatCurrency(low)}–${formatCurrency(high)}` }

export function PricingWorkspace({ capabilities, platforms, recurringServices }: { capabilities: PricingCapability[]; platforms: PricingPlatform[]; recurringServices: RecurringService[] }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const [industry, setIndustry] = useState('All')
  const categories = useMemo(() => ['All', ...Array.from(new Set(capabilities.map((item) => item.category)))], [capabilities])
  const industries = useMemo(() => ['All', ...Array.from(new Set(capabilities.flatMap((item) => item.industries)))], [capabilities])
  const filtered = capabilities.filter((item) => {
    const text = `${item.name} ${item.description} ${item.category}`.toLowerCase()
    return (!query || text.includes(query.toLowerCase())) && (category === 'All' || item.category === category) && (industry === 'All' || item.industries.includes(industry))
  })
  return <main className="min-h-dvh bg-muted/20 px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-5 border-b border-border pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Internal estimating</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Pricing & Estimates</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">A private source of truth for reusable capabilities, implementation effort, and quote ranges. Nothing here is exposed on the public site.</p></div><nav className="flex flex-wrap gap-2"><Button render={<Link href="/admin/estimating" />} variant="outline">View estimates</Button><Button render={<Link href="/admin/estimating/new" />}><Plus data-icon="inline-start" />New estimate</Button><Button variant="outline" render={<Link href="/admin/portfolio" />}>Portfolio</Button><Button variant="outline" render={<Link href="/admin/leads" />}>Leads</Button><Button variant="ghost" render={<Link href="/work" />}>View site</Button></nav></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Active capabilities</p><p className="mt-2 text-3xl font-semibold">{capabilities.length}</p></div><div className="rounded-lg border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Base platforms</p><p className="mt-2 text-3xl font-semibold">{platforms.length}</p></div><div className="rounded-lg border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Recurring services</p><p className="mt-2 text-3xl font-semibold">{recurringServices.length}</p></div></section>
    <section className="mt-8 rounded-lg border border-border bg-card"><div className="flex flex-col gap-4 border-b border-border p-4 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search capabilities" className="pl-9" /></div><select value={category} onChange={(event) => setCategory(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="All">All categories</option>{categories.slice(1).map((item) => <option key={item}>{item}</option>)}</select><select value={industry} onChange={(event) => setIndustry(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="All">All industries</option>{industries.slice(1).map((item) => <option key={item}>{item}</option>)}</select></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Capability</th><th className="px-4 py-3 font-medium">Category</th><th className="px-4 py-3 font-medium">Base / range</th><th className="px-4 py-3 font-medium">Complexity</th><th className="px-4 py-3 font-medium">Hours</th><th className="px-4 py-3 font-medium">Support</th><th className="px-4 py-3 font-medium">Industries</th><th className="px-4 py-3 font-medium">Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-b border-border/70 last:border-0"><td className="px-4 py-4"><p className="font-medium">{item.name}</p><p className="mt-1 max-w-sm text-xs text-muted-foreground">{item.description}</p></td><td className="px-4 py-4 text-muted-foreground">{item.category}</td><td className="px-4 py-4"><p className="font-medium">{formatCurrency(item.internalBasePrice)}</p><p className="text-xs text-muted-foreground">{moneyRange(item.suggestedLowPrice, item.suggestedHighPrice)}</p></td><td className="px-4 py-4"><Badge variant={item.complexity === 'High' || item.complexity === 'Custom' ? 'default' : 'secondary'}>{item.complexity}</Badge></td><td className="px-4 py-4 text-muted-foreground">{item.estimatedHoursLow}–{item.estimatedHoursHigh}h</td><td className="px-4 py-4 text-muted-foreground">{item.monthlySupportImpact}</td><td className="px-4 py-4"><div className="flex max-w-[15rem] flex-wrap gap-1">{item.industries.slice(0, 3).map((name) => <Badge key={name} variant="outline">{name}</Badge>)}{item.industries.length > 3 && <Badge variant="outline">+{item.industries.length - 3}</Badge>}</div></td><td className="px-4 py-4"><Link href={`/admin/pricing/${item.slug}`} className="text-primary hover:underline">Edit</Link></td></tr>)}</tbody></table></div>
      <div className="flex flex-col gap-3 p-4 md:hidden">{filtered.map((item) => <article key={item.id} className="rounded-md border border-border p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-xs text-muted-foreground">{item.category}</p></div><Badge variant="secondary">{item.complexity}</Badge></div><p className="mt-3 text-sm text-muted-foreground">{item.description}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Base price</p><p className="font-medium">{formatCurrency(item.internalBasePrice)}</p></div><div><p className="text-xs text-muted-foreground">Suggested range</p><p className="font-medium">{moneyRange(item.suggestedLowPrice, item.suggestedHighPrice)}</p></div><div><p className="text-xs text-muted-foreground">Effort</p><p className="font-medium">{item.estimatedHoursLow}–{item.estimatedHoursHigh}h</p></div><div><p className="text-xs text-muted-foreground">Support</p><p className="font-medium">{item.monthlySupportImpact}</p></div></div></article>)}</div>
      {!filtered.length && <p className="p-8 text-center text-sm text-muted-foreground">No capabilities match these filters.</p>}
    </section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Base project fees</p><h2 className="mt-1 text-xl font-semibold">Platforms</h2></div><ArrowRight className="text-muted-foreground" /></div><div className="mt-5 flex flex-col gap-3">{platforms.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 border-t border-border pt-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.description}</p></div><p className="shrink-0 text-sm font-medium">{moneyRange(item.suggestedLowPrice, item.suggestedHighPrice)}</p></div>)}</div></div><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Optional monthly services</p><h2 className="mt-1 text-xl font-semibold">Recurring support</h2></div><ArrowRight className="text-muted-foreground" /></div><div className="mt-5 flex flex-col gap-3">{recurringServices.slice(0, 6).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 border-t border-border pt-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.includedHours} included hours · {item.billingFrequency}</p></div><p className="shrink-0 text-sm font-medium">{formatCurrency(item.monthlyClientPrice)}/mo</p></div>)}</div></div></section>
  </div></main>
}
